apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: app
      image: fit/client
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    - name: server
      image: fit/server
      imagePullPolicy: IfNotPresent
